import "./globals.css";
import { Providers } from "./providers";
import { Analytics } from '@vercel/analytics/react';

export const metadata = {
    title: "Sudoku Solver",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="font-sans">
                <Providers>{children}</Providers>
                <Analytics mode={'production'} />
            </body>
        </html>
    );
}
